Django서버/DjangoProject-main/sitebase/myapp/urls.py
from django.urls import path, include

from . import views

app_name = 'myapp'

urlpatterns = [
    path('brand/', views.BrandListView.as_view()),
    path('brand/detail/', views.BrandDetailView.as_view()),

    path('headquarter/', views.HeadquarterView.as_view()),

    path('auth/', include('rest_framework.urls')),

    path('login/', views.LoginView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path('register/', views.RegisterView.as_view()),

    path('basetheme/', views.BaseThemeView.as_view()),
    path('customtheme/', views.CustomThemeView.as_view()),

    path('address/', views.StoreAddressView.as_view()),
    path('population/', views.PopulationListView.as_view()),
]

Django서버/DjangoProject-main/sitebase/sitebase/urls.py
from django.contrib import admin
from django.urls import path, include

# 내가 등록한 앱의 urls 을 include 해야함
urlpatterns = [
    path('myapp/', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

Django서버/DjangoProject-main/sitebase/myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class Brand(models.Model):
    # id | 업종 | 브랜드 | 상호 | 가맹사업 개시일 | 가맹사업 개월수
    id = models.CharField(max_length=8, primary_key=True)
    sector = models.CharField(max_length=16)
    brand_name = models.CharField(max_length=40)
    mutual = models.CharField(max_length=40)
    franchise_start_date = models.CharField(max_length=40)
    franchise_months = models.IntegerField()

    # 가맹점수 | 임직원수 | 신규개점 | 폐점수 | 종료수 | 명의변경
    num_of_franchise = models.IntegerField()
    num_of_employees = models.IntegerField()
    num_of_open = models.IntegerField()
    num_of_quit = models.IntegerField()
    num_of_cancel = models.IntegerField()
    num_of_name_changing = models.IntegerField()

    # 평균 매출액 | 면적 당 평균 매출액 | 가맹비 | 교육비 | 보증금 | 기타 비용
    average_sales = models.IntegerField()
    average_sales_per_area = models.IntegerField()
    franchise_fee = models.IntegerField()
    education_fee = models.IntegerField()
    deposit = models.IntegerField()
    other_cost = models.IntegerField()

    # 창업비용 | 면적당 비용 | 기준 면적 | 전체 비용
    startup_cost = models.IntegerField()
    cost_per_area = models.IntegerField()
    standard_area = models.IntegerField()
    total_cost = models.IntegerField()

    def get_absolute_url(self):
        return reverse('myapp:detail', kwargs={'pk': self.id})


class Headquarter(models.Model):
    # 5
    id = models.CharField(max_length=8, primary_key=True)
    mutual = models.CharField(max_length=40)
    representative = models.CharField(max_length=40)
    register_law_date = models.CharField(max_length=40)
    register_biz_date = models.CharField(max_length=40)

    # 6
    representative_number = models.CharField(max_length=40)
    fax_number = models.CharField(max_length=40)
    address = models.CharField(max_length=128)
    biz_type = models.CharField(max_length=40)
    law_number = models.CharField(max_length=40)
    biz_number = models.CharField(max_length=40)

    # 6
    assets_2020 = models.FloatField()
    liabilities_2020 = models.FloatField()
    equity_2020 = models.FloatField()
    sales_2020 = models.FloatField()
    income_2020 = models.FloatField()
    net_income_2020 = models.FloatField()

    # 6
    assets_2019 = models.FloatField()
    liabilities_2019 = models.FloatField()
    equity_2019 = models.FloatField()
    sales_2019 = models.FloatField()
    income_2019 = models.FloatField()
    net_income_2019 = models.FloatField()

    # 6
    assets_2018 = models.FloatField()
    liabilities_2018 = models.FloatField()
    equity_2018 = models.FloatField()
    sales_2018 = models.FloatField()
    income_2018 = models.FloatField()
    net_income_2018 = models.FloatField()

    # 6
    assets_2017 = models.FloatField()
    liabilities_2017 = models.FloatField()
    equity_2017 = models.FloatField()
    sales_2017 = models.FloatField()
    income_2017 = models.FloatField()
    net_income_2017 = models.FloatField()

    # 3
    opening_2020 = models.IntegerField()
    closing_2020 = models.IntegerField()
    name_change_2020 = models.IntegerField()

    # 3
    opening_2019 = models.IntegerField()
    closing_2019 = models.IntegerField()
    name_change_2019 = models.IntegerField()

    # 3
    opening_2018 = models.IntegerField()
    closing_2018 = models.IntegerField()
    name_change_2018 = models.IntegerField()

    # 3
    opening_2017 = models.IntegerField()
    closing_2017 = models.IntegerField()
    name_change_2017 = models.IntegerField()

    # 3
    num_of_correction = models.IntegerField()
    num_loss_of_law = models.IntegerField()
    num_of_sentences = models.IntegerField()


class StoreAddress(models.Model):
    id = models.CharField(max_length=8, primary_key=True, null=False)
    sector = models.CharField(max_length=16, null=False)
    brand_name = models.CharField(max_length=40)

    do = models.CharField(max_length=16, null=False)
    sigu = models.CharField(max_length=32, null=False)
    dong = models.CharField(max_length=16)

    longitude = models.CharField(max_length=16, null=False)
    latitude = models.CharField(max_length=16, null=False)


class Population(models.Model):
    id = models.CharField(max_length=8, primary_key=True, null=False)
    do = models.CharField(max_length=16, null=False)
    sigu = models.CharField(max_length=32, null=False)
    dong = models.CharField(max_length=16)
    population = models.IntegerField()


class UserAccountManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("email 주소가 있어야 합니다.")
        if not username:
            raise ValueError('사용자 이름이 있어야 합니다.')
        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_active = True
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    id = models.SmallAutoField(primary_key=True)
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(verbose_name='email', max_length=128, unique=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    REQUIRED_FIELDS = ['username']  # 필수입력 필드
    USERNAME_FIELD = 'email'  # 로그인 식별자

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    objects = UserAccountManager()


class AnalysisModel(models.Model):
    id = models.CharField(max_length=8, primary_key=True)

    # model
    sector = models.CharField(max_length=16)
    brand_name = models.CharField(max_length=40)
    franchise_months = models.IntegerField()

    num_of_franchise = models.IntegerField()
    average_sales = models.IntegerField()
    startup_cost = models.IntegerField()

    rate_of_opening = models.IntegerField()
    rate_of_closing = models.IntegerField()

    # ratio
    franchise_months_ratio = models.FloatField()
    num_of_franchise_ratio = models.FloatField()
    average_sales_ratio = models.FloatField()

    startup_cost_ratio = models.FloatField()
    rate_of_opening_ratio = models.FloatField()
    rate_of_closing_ratio = models.FloatField()

    label = models.IntegerField()

    def __str__(self):
        return 'id' + self.id + self.sector + self.brand_name

Django서버/DjangoProject-main/sitebase/myapp/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model, authenticate

User = get_user_model()


# class RegistrationForm(UserCreationForm):
#     email = forms.EmailField(max_length=60, help_text='유효한 이메일을 입력해주세요')
#
#     class Meta:
#         model = Account
#         fields = ("email", 'username', 'password1', 'password2')
#
#     def clean_email(self):
#         email = self.cleaned_data.get('email').lower()
#         try:
#             account = Account.objects.get(email=email)
#         except Exception as e:
#             return email
#         raise forms.ValidationError("이미 사용중인 이메일입니다.")
#
#     def clean_username(self):
#         username = self.cleaned_data.get('username')
#         try:
#             account = Account.objects.get(username=username)
#         except Exception as e:
#             return username
#         raise forms.ValidationError(f"이미 사용중인 이름입니다.")
#
#
# class AccountAuthenticationForm(forms.ModelForm):
#     password = forms.CharField(label='password', widget=forms.PasswordInput)
#
#     class Meta:
#         model = Account
#         # fields = ('username', 'password')
#         fields = ('email', 'password')
#
#     def clean(self):
#         if self.is_valid():
#             # username = self.cleaned_data.get('username')
#             email = self.cleaned_data.get('email')
#             password = self.cleaned_data.get('password')
#
#             # if not authenticate(username=username, password=password):
#             if not authenticate(email=email, password=password):
#                 raise forms.ValidationError('Invalid Login')

# class AccountUpdateform(forms.ModelForm):
#     """
#       Updating User Info
#     """
#     class Meta:
#         model  = Account
#         fields = ('email', 'username')
#         widgets = {
#                    'email':forms.TextInput(attrs={'class':'form-control'}),
#                    'password':forms.TextInput(attrs={'class':'form-control'}),
#         }
#
#     def __init__(self, *args, **kwargs):
#         """
#           specifying styles to fields
#         """
#         super(AccountUpdateform, self).__init__(*args, **kwargs)
#         for field in (self.fields['email'],self.fields['username']):
#             field.widget.attrs.update({'class': 'form-control '})
#
#     def clean_email(self):
#         if self.is_valid():
#             email = self.cleaned_data['email']
#             try:
#                 account = Account.objects.exclude(pk = self.instance.pk).get(email=email)
#             except Account.DoesNotExist:
#                 return email
#             raise forms.ValidationError("Email '%s' already in use." %email)
#     def clean_username(self):
#         if self.is_valid():
#             username = self.cleaned_data['username']
#             try:
#                 account = Account.objects.exclude(pk = self.instance.pk).get(username=username)
#             except Account.DoesNotExist:
#                 return username
#             raise forms.ValidationError("Username '%s' already in use." % username)

Django서버/DjangoProject-main/sitebase/myapp/templates/myapp/base.html
<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="/static/bootstrap.min.css" />
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>

    <body>
        <div class="container">
            {% block contents %}
            {% endblock %}
        </div>
   </body>

</html>

Django서버/DjangoProject-main/sitebase/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>프렌드차이</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<h1>브랜드 목록</h1>
{% if form.is_authenticated %}
<p>{{ user.username }}</p>
<a href="{% url 'myapp:logout' %}">로그아웃</a>
{% else %}
<a href="{% url 'myapp:login' %}">로그인</a>
<a href="{% url 'myapp:register' %}">회원가입</a>
{% endif %}
<h2>
    <a href="{% url 'myapp:brand_search' %}">브랜드 검색하기</a>
</h2>
{% if brand_list %}
<ul>
    {% for brand in brand_list %}
    <li class="card">{{brand.brand_name}}</li>
    {% endfor %}
</ul>
{% else %}
<p>No brand to show</p>
{% endif %}

<div id="main">
    <h1>Sticky Notes</h1>
    <textarea v-model="content"></textarea>
    <button @click="writeMemo">Write!</button>
    <div>
        <div class="memo" v-for="memo in memos">
            <div class="memo-delete-button"></div>
            {{ memo.content }}
        </div>
    </div>
</div>
<script>
  const app = new Vue({
    el: '#main',
    data: {
      url: 'https://http://127.0.0.1:8000/myapp/brand/',
      content: '',
      memos: [],
    },
    methods: {
      writeMemo: async function() {
        const response = await axios.post(this.url,{content : this.content})
        this.content = ''
        this.memos.push(response.data)
      },
    },
    created: async function() {
      const response = await axios.get(this.url)
      this.memos = response.data
    }
  })
</script>

<style>
.card{
    background-color: beige;
    width: 100%;
    height: 300px;
    text-align: left;

    margin-top: 10px;
}
</style>

</body>
</html>

Django서버/DjangoProject-main/sitebase/myapp/templates/myapp/kakaomap.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>좌표로 주소를 얻어내기</title>
    <style>
        .map_wrap {
            position: relative;
            width: 100%;
            height: 350px;
        }

        .title {
            font-weight: bold;
            display: block;
        }

        .hAddr {
            position: absolute;
            left: 10px;
            top: 10px;
            border-radius: 2px;
            background: #fff;
            background: rgba(255, 255, 255, 0.8);
            z-index: 1;
            padding: 5px;
        }

        #centerAddr {
            display: block;
            margin-top: 2px;
            font-weight: normal;
        }

        .bAddr {
            padding: 5px;
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
</head>

<body>
<div class="map_wrap">
    <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;"></div>
    <div class="hAddr">
        <span class="title">지도중심기준 행정동 주소정보</span>
        <span id="centerAddr"></span>
    </div>
</div>

<script type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=57f2eea55c50e7916ddc089cbd5c0051&libraries=services"></script>
<script>
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng(35.85915, 128.56298), // 지도의 중심좌표
                level: 1 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        var marker = new kakao.maps.Marker(), // 클릭한 위치를 표시할 마커입니다
            infowindow = new kakao.maps.InfoWindow({ zindex: 1 }); // 클릭한 위치에 대한 주소를 표시할 인포윈도우입니다

        // 현재 지도 중심좌표로 주소를 검색해서 지도 좌측 상단에 표시합니다
        searchAddrFromCoords(map.getCenter(), displayCenterInfo);

        // 지도를 클릭했을 때 클릭 위치 좌표에 대한 주소정보를 표시하도록 이벤트를 등록합니다
        kakao.maps.event.addListener(map, 'click', function (mouseEvent) {
            searchDetailAddrFromCoords(mouseEvent.latLng, function (result, status) {
                if (status === kakao.maps.services.Status.OK) {
                    var detailAddr = !!result[0].road_address ? '<div>도로명주소 : ' + result[0].road_address.address_name + '</div>' : '';
                    detailAddr += '<div>지번 주소 : ' + result[0].address.address_name + '</div>';

                    var content = '<div class="bAddr">' +
                        '<span class="title">법정동 주소정보</span>' +
                        detailAddr +
                        '</div>';

                    // 마커를 클릭한 위치에 표시합니다
                    marker.setPosition(mouseEvent.latLng);
                    marker.setMap(map);

                    // 인포윈도우에 클릭한 위치에 대한 법정동 상세 주소정보를 표시합니다
                    infowindow.setContent(content);
                    infowindow.open(map, marker);
                }
            });
        });

        // 중심 좌표나 확대 수준이 변경됐을 때 지도 중심 좌표에 대한 주소 정보를 표시하도록 이벤트를 등록합니다
        kakao.maps.event.addListener(map, 'idle', function () {
            searchAddrFromCoords(map.getCenter(), displayCenterInfo);
        });

        function searchAddrFromCoords(coords, callback) {
            // 좌표로 행정동 주소 정보를 요청합니다
            geocoder.coord2RegionCode(coords.getLng(), coords.getLat(), callback);
        }

        function searchDetailAddrFromCoords(coords, callback) {
            // 좌표로 법정동 상세 주소 정보를 요청합니다
            geocoder.coord2Address(coords.getLng(), coords.getLat(), callback);
        }

        // 지도 좌측상단에 지도 중심좌표에 대한 주소정보를 표출하는 함수입니다
        function displayCenterInfo(result, status) {
            if (status === kakao.maps.services.Status.OK) {
                var infoDiv = document.getElementById('centerAddr');

                for (var i = 0; i < result.length; i++) {
                    // 행정동의 region_type 값은 'H' 이므로
                    if (result[i].region_type === 'H') {
                        infoDiv.innerHTML = result[i].address_name;
                        break;
                    }
                }
            }
        }

</script>
</body>

</html>

Django서버/DjangoProject-main/sitebase/myapp/templates/myapp/login.html
<!DOCTYPE html>
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <title>프렌드차이 로그인</title>
</head>
<body>
<h2>로그인</h2>
{% block content %}
<div class="container my-3">
    {{ message }}
    <form method="post" action="{% url 'myapp:login' %}">
        {% csrf_token %}
        Email
        <input type="email" name="email" class="form-control" required>
        </br>
        password
        <input type="password" name="password" class="form-control" required>
        </br>
        <button type="submit" value="로그인">로그인</button>
    </form>
</div>
{% endblock %}
</body>
</html>

Django서버/DjangoProject-main/sitebase/myapp/templates/myapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>회원가입</h2>
<form method="POST" action="{% url 'myapp:register' %}">
    {% csrf_token %}
    Email
    <input type="email" name="email" class="form-control" required>
    </br>
    username
    <input type="text" name="username" class="form-control" required>
    </br>
    password1
    <input type="password" name="password1" class="form-control" required>
    </br>
    password2
    <input type="password" name="password2" class="form-control" required>
    </br>

    {% for field in form %}
    <p>
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <input type="submit" value="회원가입">
</form>
</body>
</html>